# please keep this alphabetized
linters:
  enable:
    - asciicheck
    - contextcheck
    - forcetypeassert
    - gocritic
    - godot
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - stylecheck
    - staticcheck
  skip-files:
    - "zz_generated.*\\.go$"
  skip-dirs:
    - pkg/client
    - pkg/openapi
    - pkg/apis/example.com/gpu/v1alpha1/zz_generated.deepcopy.go
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true
  new-from-rev: HEAD
  uniq-by-line: false
  fix: true
  allow-parallel-runners: true

run:
  tests: true
  timeout: 1m

linters-settings:
  goimports:
    local-prefixes: "Ascend-dra-driver"
