---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dra-example-driver.fullname" . }}-role
  namespace: {{ include "dra-example-driver.namespace" . }}
rules:
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclaims"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["nodes", "namespaces"]
  verbs: ["get", "create", "list"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceslices", "deviceclasses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
